### ISSUE TITLE
Data downloads are too big for clinvar download

### ISSUE THREAD

**Issue by svsuresh** [biobricks-ai/biobricks#11]
I see that just to set up clinvar, as outlined in tutorial, user needs to download 1 GB.  It is helpful to denote how much HDD space is needed for each reference. Such big files for small files like clinvar (clinvar.vcf) surprised me and also huge files with random numbers are not welcome, for my purpose. I stalled installation there.  Here is the screenshot for setting clinvar:

<a href="https://ibb.co/vsBcHRb"><img src="https://i.ibb.co/mvBRGgm/clinivar-bb.png" alt="clinivar-bb" border="0"></a>

**Comment by tomlue** [comment]
It is true that many biobricks are large. The clinvar brick collects data from https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited, which is a bit larger than 1gb. 

Do you have a suggested solution for this issue? 

**huge files with random numbers are not welcome**
The biobricks system works by creating files with filenames based on content hashes, that is the reason for the seemingly random file names, this comes from our dependency on dvc. In practice, you shouldn't need to worry about these names in your work.

**Comment by tomlue** [comment]
status.biobricks.ai now makes the size of the assets clear.
